### ISSUE TITLE
Failed to open the USB port!

### ISSUE THREAD

**Issue by texhz** [RDzRyan/src#21]

**Comment by texhz** [comment]
Hi,

I am quite new to this and any help would be appre
When running the following command:

`roslaunch hexapod_bringup hexapod_simple.launch`

I come across the following issue.

Current: speed 0.5000006 turn 0.500000 | Awaiting command...
[ WARN] [1648892311.054960729]: Failed to open the USB port!, Ignore if using Rviz or Gazbebo
[ INFO] [1648892314.538492023]:

**Comment by RDzRyan** [comment]
> Hi,
> 
> I am quite new to this and any help would be appre When running the following command:
> 
> `roslaunch hexapod_bringup hexapod_simple.launch`
> 
> I come across the following issue.
> 
> Current: speed 0.5000006 turn 0.500000 | Awaiting command... [ WARN] [1648892311.054960729]: Failed to open the USB port!, Ignore if using Rviz or Gazbebo [ INFO] [1648892314.538492023]:

Sorry for the inconvenience, this project is forked from github.com/KevinOchs/hexapod_ros, I edit some programs as per my requirement. I suggest you to use the original program. thank you 😉

**Comment by RDzRyan** [comment]
If you still have questions, don't hesitate to ask

**Comment by RDzRyan** [comment]
> Hi,
> 
> I am quite new to this and any help would be appre When running the following command:
> 
> `roslaunch hexapod_bringup hexapod_simple.launch`
> 
> I come across the following issue.
> 
> Current: speed 0.5000006 turn 0.500000 | Awaiting command... [ WARN] [1648892311.054960729]: Failed to open the USB port!, Ignore if using Rviz or Gazbebo [ INFO] [1648892314.538492023]:

BTW, The usb port is used for the dynamixel servo driver on the port  ttyUSB that you can set on /src/hexapod_controller/include/servo_driver.h
